export enum ResponseMessageKey {
  // region Success Messages
  BOOKS_RETRIEVED = 'BOOKS_RETRIEVED',
  BOOK_RETRIEVED = 'BOOK_RETRIEVED',
  HIGHLIGHTS_RETRIEVED = 'HIGHLIGHTS_RETRIEVED',
  HIGHLIGHT_RETRIEVED = 'HIGHLIGHT_RETRIEVED',
  HIGHLIGHT_DELETED = 'HIGHLIGHT_DELETED',
  HIGHLIGHT_CREATED = 'HIGHLIGHT_CREATED',
  NOTE_ADDED = 'NOTE_ADDED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  NOTE_DELETED = 'NOTE_DELETED',
  // endregion

  // region Error Messages
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // endregion
}
